import {
  Car,
  Building,
  Stethoscope,
  FileText,
  User,
  Heart,
  Brain,
  Bone,
  Eye,
  Blinds as Lungs,
} from "lucide-react"

export const injuryCategories = [
  { id: "mva", label: "Motor Vehicle Accident (MVA)", icon: Car, color: "bg-red-100 text-red-700" },
  { id: "slip-fall", label: "Slip and Fall", icon: Building, color: "bg-orange-100 text-orange-700" },
  { id: "med-malpractice", label: "Medical Malpractice", icon: Stethoscope, color: "bg-blue-100 text-blue-700" },
  { id: "product-liability", label: "Product Liability", icon: FileText, color: "bg-green-100 text-green-700" },
  { id: "workplace", label: "Workplace Injury", icon: Building, color: "bg-purple-100 text-purple-700" },
  { id: "assault", label: "Assault/Battery", icon: User, color: "bg-gray-100 text-gray-700" },
]

export const mvaSubCategories = [
  "Car vs. Car",
  "Car vs. Pedestrian",
  "Car vs. Bicycle",
  "Car vs. Motorcycle",
  "Truck/Commercial Vehicle",
  "Rideshare/Uber/Lyft",
]

export const slipFallSubCategories = [
  "Wet/Slippery Surface",
  "Uneven Surface/Trip Hazard",
  "Inadequate Lighting",
  "Defective Stairs/Handrails",
  "Ice/Snow Related",
  "Debris/Objects on Floor",
]

export const medMalpracticeSubCategories = [
  "Surgical Error",
  "Misdiagnosis/Delayed Diagnosis",
  "Medication Error",
  "Birth Injury",
  "Anesthesia Error",
  "Hospital Negligence",
]

export const productLiabilitySubCategories = [
  "Defective Design",
  "Manufacturing Defect",
  "Inadequate Warning/Instructions",
  "Pharmaceutical/Drug",
  "Medical Device",
  "Consumer Product",
]

export const workplaceSubCategories = [
  "Construction Accident",
  "Machinery/Equipment Injury",
  "Fall from Height",
  "Chemical Exposure",
  "Repetitive Stress Injury",
  "Workplace Violence",
]

export const assaultSubCategories = [
  "Physical Assault",
  "Sexual Assault",
  "Domestic Violence",
  "Bar/Nightclub Incident",
  "Road Rage",
  "Security Negligence",
]

export const bodySystemsAffected = [
  { id: "neurological", label: "Neurological", description: "Brain, spine, nerves", icon: Brain },
  { id: "orthopedic", label: "Orthopedic", description: "Bones, joints, muscles", icon: Bone },
  { id: "cardiovascular", label: "Cardiovascular", description: "Heart, circulation", icon: Heart },
  { id: "respiratory", label: "Respiratory", description: "Lungs, breathing", icon: Lungs },
  { id: "psychological", label: "Psychological", description: "Mental health, PTSD", icon: Brain },
  { id: "internal", label: "Internal Organs", description: "Liver, kidney, etc.", icon: Heart },
  { id: "dermatological", label: "Dermatological", description: "Burns, scarring", icon: Eye },
]

export const documentRequirements = {
  mva: {
    "Car vs. Car": [
      "Police Report (required within 24 hours)",
      "Emergency Medical Services (EMS/Ambulance) Report",
      "Emergency Room Records",
      "Hospital Admission Records (if applicable)",
      "Radiology Reports (X-rays, CT, MRI)",
      "Primary Care Physician Records",
      "Specialist Consultation Reports",
      "Physical Therapy Records",
      "Pharmacy Records",
      "Insurance Documentation",
      "Vehicle Damage Photos",
      "Traffic Camera Footage (if available)",
    ],
    "Car vs. Pedestrian": [
      "Police Report",
      "Emergency Medical Treatment Records",
      "Trauma Center Records",
      "Orthopedic/Neurological Specialist Reports",
      "Rehabilitation Records",
      "Witness Statements",
      "Traffic Signal/Crosswalk Documentation",
      "Surveillance Footage",
    ],
    "Car vs. Bicycle": [
      "Police Report",
      "Emergency Medical Records",
      "Orthopedic Treatment Records",
      "Bicycle Damage Assessment",
      "Helmet/Safety Equipment Documentation",
      "Road Condition Reports",
    ],
    "Car vs. Motorcycle": [
      "Police Report",
      "Emergency Medical Records",
      "Trauma Surgery Records",
      "Motorcycle Damage Assessment",
      "Protective Gear Documentation",
      "Road Surface Analysis",
    ],
    "Truck/Commercial Vehicle": [
      "Police Report",
      "DOT Driver Logs",
      "Vehicle Inspection Records",
      "Commercial Insurance Documentation",
      "Company Safety Records",
      "Emergency Medical Records",
      "Cargo Manifest (if applicable)",
    ],
    "Rideshare/Uber/Lyft": [
      "Police Report",
      "Rideshare Company Insurance",
      "Driver Background Check Records",
      "Vehicle Inspection Records",
      "Trip Documentation",
      "Emergency Medical Records",
    ],
  },
  "slip-fall": {
    "Wet/Slippery Surface": [
      "Incident Report (property owner/manager)",
      "Emergency Medical Treatment Records",
      "Property Maintenance Records",
      "Cleaning Logs/Schedules",
      "Weather Reports (if outdoor)",
      "Surveillance Footage",
      "Witness Statements",
    ],
    "Uneven Surface/Trip Hazard": [
      "Incident Report",
      "Property Inspection Records",
      "Construction/Repair Documentation",
      "Code Violation Reports",
      "Emergency Medical Records",
      "Photos of Hazard",
    ],
    "Inadequate Lighting": [
      "Incident Report",
      "Lighting Maintenance Records",
      "Electrical Inspection Reports",
      "Emergency Medical Records",
      "Light Level Measurements",
    ],
    "Defective Stairs/Handrails": [
      "Building Inspection Reports",
      "Construction/Installation Records",
      "Code Compliance Documentation",
      "Maintenance Records",
      "Emergency Medical Records",
    ],
    "Ice/Snow Related": [
      "Weather Reports",
      "Snow Removal Contracts/Logs",
      "Salt/De-icing Records",
      "Property Maintenance Documentation",
      "Emergency Medical Records",
    ],
    "Debris/Objects on Floor": [
      "Incident Report",
      "Cleaning/Maintenance Schedules",
      "Store/Property Surveillance",
      "Employee Training Records",
      "Emergency Medical Records",
    ],
  },
  "med-malpractice": {
    "Surgical Error": [
      "Complete Medical Records",
      "Surgical Reports/Notes",
      "Anesthesia Records",
      "Pre/Post-Operative Records",
      "Pathology Reports",
      "Radiology/Imaging Studies",
      "Hospital Policies/Procedures",
      "Staff Credentials/Training",
    ],
    "Misdiagnosis/Delayed Diagnosis": [
      "Complete Medical Records",
      "Diagnostic Test Results",
      "Consultation Reports",
      "Radiology Reports",
      "Laboratory Results",
      "Referral Documentation",
      "Treatment Timeline",
    ],
    "Medication Error": [
      "Pharmacy Records",
      "Prescription Documentation",
      "Medical Records",
      "Drug Interaction Warnings",
      "Dosage Calculations",
      "Administration Records",
    ],
    "Birth Injury": [
      "Prenatal Records",
      "Labor/Delivery Records",
      "Fetal Monitoring Strips",
      "Newborn Records",
      "NICU Documentation",
      "Pediatric Neurology Reports",
    ],
    "Anesthesia Error": [
      "Anesthesia Records",
      "Pre-operative Assessment",
      "Monitoring Records",
      "Equipment Maintenance Logs",
      "Staff Credentials",
      "Emergency Response Documentation",
    ],
    "Hospital Negligence": [
      "Hospital Records",
      "Nursing Notes",
      "Medication Administration Records",
      "Incident Reports",
      "Staff Training Records",
      "Hospital Policies",
    ],
  },
  "product-liability": {
    "Defective Design": [
      "Product Documentation",
      "Design Specifications",
      "Safety Testing Reports",
      "Regulatory Approvals",
      "Similar Incident Reports",
      "Expert Analysis Reports",
    ],
    "Manufacturing Defect": [
      "Product Sample/Evidence",
      "Manufacturing Records",
      "Quality Control Documentation",
      "Batch/Lot Information",
      "Inspection Reports",
      "Recall Notices (if any)",
    ],
    "Inadequate Warning/Instructions": [
      "Product Packaging/Labels",
      "User Manuals/Instructions",
      "Safety Warnings",
      "Marketing Materials",
      "Regulatory Requirements",
      "Industry Standards",
    ],
    "Pharmaceutical/Drug": [
      "Prescription Records",
      "FDA Approval Documentation",
      "Clinical Trial Data",
      "Adverse Event Reports",
      "Package Inserts",
      "Medical Records",
    ],
    "Medical Device": [
      "Device Documentation",
      "FDA Clearance/Approval",
      "Implantation/Usage Records",
      "Maintenance Records",
      "Malfunction Reports",
      "Medical Records",
    ],
    "Consumer Product": [
      "Product Sample",
      "Purchase Documentation",
      "Safety Standards Compliance",
      "Consumer Complaints",
      "Recall Information",
      "Injury Documentation",
    ],
  },
  workplace: {
    "Construction Accident": [
      "OSHA Incident Report",
      "Safety Training Records",
      "Equipment Inspection Logs",
      "Site Safety Plans",
      "Workers' Compensation Claims",
      "Medical Treatment Records",
      "Witness Statements",
    ],
    "Machinery/Equipment Injury": [
      "Equipment Maintenance Records",
      "Safety Training Documentation",
      "OSHA Reports",
      "Equipment Manuals/Warnings",
      "Lockout/Tagout Procedures",
      "Medical Records",
    ],
    "Fall from Height": [
      "Safety Harness/Equipment Records",
      "Fall Protection Plans",
      "Training Documentation",
      "OSHA Citations",
      "Medical Treatment Records",
      "Site Inspection Reports",
    ],
    "Chemical Exposure": [
      "Material Safety Data Sheets (MSDS)",
      "Exposure Monitoring Records",
      "Personal Protective Equipment Logs",
      "Medical Surveillance Records",
      "OSHA Reports",
      "Toxicology Reports",
    ],
    "Repetitive Stress Injury": [
      "Ergonomic Assessments",
      "Job Description/Requirements",
      "Medical Records",
      "Physical Therapy Documentation",
      "Workplace Modification Records",
      "Workers' Compensation Claims",
    ],
    "Workplace Violence": [
      "Incident Reports",
      "Security Records/Footage",
      "Employee Background Checks",
      "Workplace Violence Policies",
      "Medical/Psychological Records",
      "Police Reports",
    ],
  },
  assault: {
    "Physical Assault": [
      "Police Report",
      "Emergency Medical Records",
      "Criminal Case Documentation",
      "Witness Statements",
      "Surveillance Footage",
      "Medical Treatment Records",
      "Psychological Evaluation",
    ],
    "Sexual Assault": [
      "Police Report",
      "Medical Examination Records",
      "Counseling/Therapy Records",
      "Criminal Case Files",
      "Expert Testimony Documentation",
      "Psychological Treatment Records",
    ],
    "Domestic Violence": [
      "Police Reports",
      "Medical Records",
      "Protective Order Documentation",
      "Counseling Records",
      "Witness Statements",
      "Photos of Injuries",
    ],
    "Bar/Nightclub Incident": [
      "Police Report",
      "Security Footage",
      "Incident Reports",
      "Alcohol Service Records",
      "Security Training Documentation",
      "Medical Records",
    ],
    "Road Rage": [
      "Police Report",
      "Traffic Camera Footage",
      "Vehicle Damage Documentation",
      "Medical Records",
      "Witness Statements",
      "Criminal Case Files",
    ],
    "Security Negligence": [
      "Security Company Records",
      "Training Documentation",
      "Incident Reports",
      "Property Security Assessments",
      "Surveillance Systems Documentation",
      "Medical Records",
    ],
  },
}
